[package]
name = "VocabPop"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
winrt-notification = "=0.5.1"
rand = "0.8"
ctrlc = "3"
tray-item = "0.6"
